import {
  arbitrum,
  avalanche,
  base,
  bsc,
  chiliz,
  cronos,
  fantom,
  flowMainnet,
  gnosis,
  linea,
  lisk,
  mainnet,
  moonbeam,
  optimism,
  polygon,
  pulsechain,
  ronin,
  sei,
} from 'viem/chains'

export const CHAIN_MORALIS_SUPPORT = {
  [mainnet.id]: 'eth',
  [polygon.id]: '0x89',
  [bsc.id]: 'bsc',
  [arbitrum.id]: 'arbitrum',
  [base.id]: 'base',
  [optimism.id]: 'optimism',
  [linea.id]: 'linea',
  [avalanche.id]: 'avalanche',
  [fantom.id]: 'fantom',
  [cronos.id]: 'cronos',
  [gnosis.id]: 'gnosis',
  [chiliz.id]: 'chiliz',
  [moonbeam.id]: 'moonbeam',
  [flowMainnet.id]: 'flow',
  [ronin.id]: 'ronin',
  [lisk.id]: 'lisk',
  [pulsechain.id]: 'pulse',
  [sei.id]: 'sei',
}
