export enum KEY_REACT_QUERY {
  getBalancesTokenByAddress = 'getBalancesTokenByAddress',
  getBalancesTokenImportByAddress = 'getBalancesTokenImportByAddress',
  getTokenPrice = 'getTokenPrice',
  getNFTsByWallet = 'getNFTsByWallet',
  getCollectionsByWallet = 'getCollectionsByWallet',
  getNFtDetail = 'getNFtDetail',
  getTypeUrlImage = 'getTypeUrlImage',
  getNftMetadataEVM = 'getNftMetadataEVM',
  getEstimateGas = 'getEstimateGas',
  getBalanceNative = 'getBalanceNative',
  getABIContract = 'getABIContract',
  getDecodeTx = 'getDecodeTx',
  getExchangeToken = 'getExchangeToken',
  getIsContract = 'getIsContract',
  getInfoToken = 'getInfoToken',
  getChainList = 'getChainList',
}
