export enum KEY_STORAGE {
  Language = 'Language',
  Mode = 'Mode',
  Notification = 'notification',
  'keyEncrypt' = 'keyEncrypt',
  'UserData' = 'UserData',
  'AccessToken' = 'AccessToken',
  'RefreshToken' = 'RefreshToken',
  'WalletConnect' = 'WalletConnect',
  Mnemonic = 'Mnemonic',
  ListChain = 'ListChain',
  AllWallet = 'AllWallet',
  Sessions = 'Sessions',
  PasscodeAuth = 'PasscodeAuth',
  ListTokenImport = 'ListTokenImport',
  BalanceTokenLocal = 'balanceTokenLocal',
  ListTokenImportLocal = 'ListTokenImportLocal',
}
